# Cody Tolene
# Apache License 2.0

import uasyncio
from utils.sounds import ExampleMusic


class NyanCat:
    def __init__(
        self,
        galactic_unicorn,
        options_service,
        pico_graphics,
        sound_service,
        wifi_service,
    ):
        self.frame_index = 0
        self.galactic_unicorn = galactic_unicorn
        self.options_service = options_service
        self.pico_graphics = pico_graphics
        self.sound_service = ExampleMusic(galactic_unicorn, sound_service)
        self.wifi_service = wifi_service

        self.sound_service.play()

    def display_frame(self, frame):
        for y, row in enumerate(frame):
            for x, char in enumerate(row):
                color = color_key.get(char, (0, 0, 0))
                pen = self.pico_graphics.create_pen(*color)
                self.pico_graphics.set_pen(pen)
                self.pico_graphics.pixel(x, y)
        self.galactic_unicorn.update(self.pico_graphics)

    async def update(self):
        self.pico_graphics.set_pen(self.pico_graphics.create_pen(0, 0, 0))
        self.pico_graphics.clear()

        self.display_frame(frames[self.frame_index])
        self.frame_index = (self.frame_index + 1) % len(frames)


async def run(
    galactic_unicorn, options_service, pico_graphics, sound_service, wifi_service
):
    nyan_cat = NyanCat(
        galactic_unicorn, options_service, pico_graphics, sound_service, wifi_service
    )

    while True:
        await nyan_cat.update()
        await uasyncio.sleep(0.1)


color_key = {
    "R": (255, 0, 0),  # Red
    "O": (255, 165, 0),  # Orange
    "Y": (255, 255, 0),  # Yellow
    "G": (0, 255, 0),  # Green
    "B": (0, 0, 255),  # Blue
    "I": (75, 0, 130),  # Indigo
    "V": (238, 130, 238),  # Violet
    "W": (255, 255, 255),  # White
    "C": (0, 255, 255),  # Cyan
    "P": (255, 192, 203),  # Pink
    " ": (0, 0, 0),  # Black (space)
}

frames = [
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "OOOOORRRRRRROOOOORRIPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "YYYYYOOOOOOYYYYOOYOIPVVVVVVVIIIVVP III IIIIIIIIIIIIII",
        "GGGGGYYYYYYGGGGIIOOIPVVVVVVVIPPIIIIPVVI IIIIIIIIIIIII",
        "CCCCCCCCCCCCCCCBIIIIPVVVVVVIVPVIVIIIIPI IIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBBBBIIIVIVIIVIIIIII IIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIII IIIII IIII     I  IIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIII  I   IIIIIIIIIIIIIIIIIIIII",
        "RRRRRRROOOOORRRRRRRRPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "OOOOOOYYYYYYOOOOOOOIPVVVVVVVVIVVVP  II IIIIIIIIIIIIII",
        "YYYYYYGGGGGGYYYYYYGIPVVVVVVVIPPIIIIVPI IIIIIIIIIIIIII",
        "CCCCCCCCCCCCCCG II IPVVVVVVIVPVIPVIVIPI IIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBIIII PPVVVVVVIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIII I   I  II  I   I  IIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIII   I   IIIIIIIIIIIIIIIIIIIII",
        "RRRRRROOOOORRRRRRRRRPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "OOOOOYYYYYYOOOOOOYOIPVVVVVVVVIVVVP  II IIIIIIIIIIIIII",
        "YYYYYGGGGGGYYYYYYGGIPVVVVVVVIPPIIIIVPI IIIIIIIIIIIIII",
        "CCCCCCCCCCCCCCGGIIIIPVVVVVVIVPVIPVIVIPI IIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBIIIIIPPVVVVVVIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIII II  I   II II  I  IIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIII      I   IIIIIIIIIIIIIIIIIIIII",
        "OOOOOORRRRRRROOOOORIPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "YYYYYYOOOOOOYYYYYYOIPVVVVVVVIVVVVP II IIIIIIIIIIIIIII",
        "GGGGGGYYYYYYGGIIIGOIPVVVVVVIVPIIIIIPP  IIIIIIIIIIIIII",
        "CCCCCCCCCCCCCCBBIIIIPVVVVVIIPPIVPIPIVV IIIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBBBII PPVVVVVIIVIIIIIIII IIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIII III I  I II I   I IIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIII      II  IIIIIIIIIIIIIIIIIIIII",
        "OOOOORRRRRRROOOOORRIPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "YYYYYOOOOOOYYYYOOYOIPVVVVVVIIIVVVP II IIIIIIIIIIIIIII",
        "GGGGGYYYYYYGGGGIIOOIPVVVVVVIPPIIIIPPVI IIIIIIIIIIIIII",
        "CCCCCCCCCCCCCCCBIIIIPVVVVVIIPPIIIIIIPV IIIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBBBII PPVVVVVVIIII IIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIII III  I I II     I IIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "RRRRRRROOOOORRRRRRRIPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "OOOOOOYYYYYYOOOOOOOIPVVVVVVIIIVVVP II IIIIIIIIIIIIIII",
        "YYYYYYGGGGGGYYG II IPVVVVVVIPPIIIIPPVI IIIIIIIIIIIIII",
        "CCCCCCCCCCCCCCCCIIIIPVVVVVIIPPIIIIIIPV IIIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBBBBIIIIIVVVIIIIII IIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIII     IIII I III IIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "RRRRRROOOOORRRRRRRRIPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "OOOOOYYYYYYOOOOOOYOIPVVVVVVVIIIVVP III IIIIIIIIIIIIII",
        "YYYYYGGGGGGYYYGIIGGIPVVVVVVVIPPIIIIPVVI IIIIIIIIIIIII",
        "CCCCCCCCCCCCCCCCIIIIPVVVVVVIVPVIVIIIIPI IIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBBBBIIIIIVIVVIIIIII IIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIII I      III     I  IIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIII  I   IIIIIIIIIIIIIIIIIIIII",
        "OOOOOORRRRRRROOOOORIPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "YYYYYYOOOOOOYYYYYYOIPVVVVVVVVIVVVP  II IIIIIIIIIIIIII",
        "GGGGGGYYYYYYGGGGGGGIPVVVVVVVIPPIIIIVPI IIIIIIIIIIIIII",
        "CCCCCCCCCCCCCCIIII IPVVVVVVIVPVIPVIVIPI IIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBIIIIIPPVVVVVVIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIII I   I  II  I III  IIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIII      I   IIIIIIIIIIIIIIIIIIIII",
        "OOOOORRRRRRROOOOORRIPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "YYYYYOOOOOOYYYYYYYOIPVVVVVVVVIVVVP  II IIIIIIIIIIIIII",
        "GGGGGYYYYYYGGGGGGYOIPVVVVVVVIPPIIIIVPI IIIIIIIIIIIIII",
        "CCCCCCCCCCCCCCCIIIIIPVVVVVVIVPVIPVIVIPI IIIIIIIIIIIII",
        "BBBBBBBBBBBBBBIIIIIIPPVVVVVVIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIII II  I  IIII I  I  IIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIII  I   IIIIIIIIIIIIIIIIIIIII",
        "RRRRRRROOOOORRRRRRRRPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "OOOOOOYYYYYYOOOOOOOIPVVVVVVVIVVVVP II IIIIIIIIIIIIIII",
        "YYYYYYGGGGGGYYOOIO IPVVVVVVIVPIIIIIPP  IIIIIIIIIIIIII",
        "CCCCCCCCCCCCCCCIBIIIPVVVVVIIPPIVPIPIVV IIIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBBBIIIPPVVVVVIIVIIIIIIII IIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIII I   I IIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
    [
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIII  III  IIIIIIIIIIIIIIIIIIIII",
        "RRRRRROOOOORRRRRRRRRPPVVVVVVVVVVPP IIIIIIIIIIIIIIIIII",
        "OOOOOYYYYYYOOOOOOYOIPVVVVVVIIIVVVP II IIIIIIIIIIIIIII",
        "YYYYYGGGGGGYYYGIIGGIPVVVVVVIPPIIIIPPVI IIIIIIIIIIIIII",
        "CCCCCCCCCCCCCCCCIIIIPVVVVVIIPPIIIIIIPV IIIIIIIIIIIIII",
        "BBBBBBBBBBBBBBBBBIIIPPVVVVVVIIII IIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIII  I I II     I IIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
        "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    ],
]
